# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

junit_version=5.10.0-M1
mixinextras_version=0.4.1

mod_id=modernfix
minecraft_version=1.21.10
enabled_platforms=neoforge,fabric
neoforge_version=21.10.51-beta
parchment_version=2025.10.12
parchment_mc_version=1.21.10
refined_storage_version=4392788
jei_version=26.1.0.16
rei_version=13.0.678
ctm_version=5587515
ldlib_version=5782845
kubejs_version=2101.7.1-build.181
rhino_version=2101.2.7-build.74
supported_minecraft_versions=1.21.10

fabric_loader_version=0.18.0
fabric_api_version=0.138.3+1.21.10

continuity_version=3.0.1-beta.2+1.21.10

modmenu_version=16.0.0-rc.1
diagonal_fences_version=7084323

spark_version=7094485

use_fabric_api_at_runtime=true

# Look up maven coordinates when changing shadow_version
shadow_version=7.1.2

mgv=21.10.1
